version: "3.8"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: deploy_lens_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - deploy_lens_db_data:/var/lib/postgresql/data

volumes:
  deploy_lens_db_data:
